### ISSUE TITLE
推荐部分资源

### ISSUE THREAD

**Issue by h7ml** [ninvfeng/chatgpts#3]
https://chat.theb.ai/

https://chatforai.com/

https://poe.com/

https://chatgpt.poshist.cn/

https://gpt.h7ml.cn/

https://chat.wxredcover.cn/

https://chat.yqcloud.top/

https://chat.xeasy.me/

https://chat.forchange.cn/

https://chat.xeasy.me/

https://chat.jingran.vip/

https://chat.aigc-model.com/

https://chat.qingting.work/

https://chat.geekr.dev/

https://desk.im/

https://chatgpt.h7ml.cn/

https://xc.com/

https://chat.51buygpt.com/

https://freechatgpt.chat/

https://askai.ws/

https://ai.yiios.com/

http://chat.apigpt.cn/

https://94gpt.com/

https://www.teach-anything.com/

http://itecheasy.com.cn/

https://trychatgp.com/

https://chatgpt.ddiu.io/

https://ai117.com/

http://chat.livepo.top/

https://freechatgpt.lol/

https://freegpt.cc/

https://ai.ls/

https://chat.alpaca-bi.com/

https://chat.paoying.net/

https://chat.eaten.fun/

https://www.askopenai.cn/

https://chat.h7ml.cn/

https://chatgpt-flutter.h7ml.cn/

https://www.aitoolgpt.com/

**Comment by ninvfeng** [comment]
感谢❤️

**Comment by ninvfeng** [comment]
哇, 你这个 [本站拥有 113 个 key,请放心使用] 太优秀了 👍🏻

**Comment by liusishan** [comment]
https://chat.xeasy.me/，这个已经被墙了 可以换成
https://chat1.xeasy.me/
https://gpt.xeasy.me/

**Comment by ninvfeng** [comment]
> [https://chat.xeasy.me/，这个已经被墙了](https://chat.xeasy.me/%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%B7%B2%E7%BB%8F%E8%A2%AB%E5%A2%99%E4%BA%86) 可以换成 https://chat1.xeasy.me/ https://gpt.xeasy.me/

好的

**Comment by clayboby** [comment]
请求收录，注册就送GPT4使用码：TRYGPT4
https://chat.zhenbs.com/
微信登录后，每天都免费用，注册就送GPT4试用。也可游客体验
每邀请一个人增加一次GPT4的使用次数，外加送GPT3五次和余额赠送
公众号还有各种福利，实现3.5和4的使用
